name: eduventure
description: "eduventure"
publish_to: 'none'

version: 1.0.14+14

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: 0.27.5
  dio: 5.7.0
  logger: 1.1.0
  get_it: 7.2.0
  intl: 0.19.0
  top_snackbar_flutter: 3.1.0
  retrofit: 4.4.1
  dots_indicator: 2.1.0
  json_annotation: 4.8.1
  hive_flutter: 1.1.0
  path_provider: 2.1.5
  flutter_svg: ^2.0.17
  flutter_svg_provider: ^1.0.3
  expandable: 5.0.1
  image_picker: 0.8.5+3
  permission_handler: 11.3.1
  cached_network_image: 3.3.1
  url_launcher: 6.3.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  package_info_plus: 8.3.0
  crypto: ^3.0.3
  flutter_rating_bar: 4.0.1
  shared_preferences: 2.2.2
  device_info_plus: 10.1.1
  carousel_slider: 5.0.0
  collection: 1.19.0
  flutter_html_math: 3.0.0
  flutter_html: ^3.0.0
  pie_chart: ^5.2.1
  connectivity_plus: 6.1.4
  file_picker: 10.1.2
  webview_flutter: 4.11.0
  video_player: 2.10.0
  chewie: 1.8.0
#  better_player: 0.0.84


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: 9.1.5
  hive_generator: 2.0.1
  build_runner: ^2.4.14
  json_serializable: ^6.7.1
  flutter_launcher_icons: 0.13.1

dependency_overrides:
  path_provider: 2.1.5



flutter_icons:
  android: true
  ios: true
  image_path: "asset/launcher.png"



# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/logo.png
    - asset/login_bag.png
    - asset/arrow.png
    - asset/home_back.png
    - asset/notif.png
    - asset/eye.png
    - asset/filtr_icon.png
    - asset/but_1.svg
    - asset/but_2.svg
    - asset/but_3.svg
    - asset/but_4.svg
    - asset/but_5.svg
    - asset/packets.png
    - asset/date_ic.png
    - asset/reyt_1.png
    - asset/reyt_2.png
    - asset/reyt_3.png
    - asset/quiz_icon.png
    - asset/search_stud_bag.png
    - asset/success.png
    - asset/tex_not.png
    - asset/vec_img.png
    - asset/category_navigate.png
    - asset/metn.png
    - asset/previe.png
    - asset/launcher.png
    - asset/result_1.png
    - asset/result_2.png
    - asset/result_3.png
    - asset/result_4.png
    - asset/result_5.png
    - asset/notiv_ic.png
    - asset/request.png
    - asset/settings.png
    - asset/prof_1.png
    - asset/prof_2.png
    - asset/prof_3.png
    - asset/prof_4.png
    - asset/prof_5.png
    - asset/prof_6.png
    - asset/prof_7.png
    - asset/file_downlide.png
    - asset/az-min.png
    - asset/home_search.svg
    - asset/cont_5.png
    - asset/cont_4.png
    - asset/cont_3.png
    - asset/cont_2.png
    - asset/cont_1.png
    - asset/vent_icon.png
    - asset/exam1.png
    - asset/exam2.png
    - asset/exam3.png
    - asset/exam4.png
    - asset/balans_back.png
    - asset/premium.png
    - asset/clas_ic.png
    - asset/testler.png
    - asset/chat_bot.png
    - asset/bot-removebg-preview.png
    - asset/quziler.png
    - asset/umumi_sinaq.png
    - asset/mÑŒsabiqeler.png
    - asset/buraxilis_imtahan blok.png
    - asset/access_bag.png
    - asset/video_bag.png
flutter_intl:
  enabled: true

